environment:
  matrix:
    - nodejs_version: "7"
    OPENSSL_VERSION: 1_0_2o
    - nodejs_version: "8"
    OPENSSL_VERSION: 1_0_2o
    - nodejs_version: "9"
    OPENSSL_VERSION: 1_0_2o


os: Visual Studio 2015
platform: x64

cache:
  - node_modules


install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
    # install OpenSSL
  - mkdir C:\OpenSSL
  - ps: if (Test-Path env:OPENSSL_VERSION) { Start-FileDownload "http://slproweb.com/download/Win64OpenSSL-${env:OPENSSL_VERSION}.exe" }
  - if defined OPENSSL_VERSION Win64OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"

test_script:
  - npm test

build: off
